# path: KChart2/kchart_core/pubspec.yaml

name: kchart_core
description: Core logic for kchart, including data structures and compute engine.
version: 0.1.0-dev.1
resolution: workspace
publish_to: none
repository: https://github.com/Informatica-ASHware/KChart2
homepage: https://github.com/Informatica-ASHware/KChart2/tree/main/packages/kchart_core
issue_tracker: https://github.com/Informatica-ASHware/KChart2/issues

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  meta: any
  freezed_annotation: any
  json_annotation: any

dev_dependencies:
  build_runner: any
  freezed: any
  json_serializable: any
  test: any
  glados: any
