import 'package:freezed_annotation/freezed_annotation.dart';

part 'ai_models.freezed.dart';

/// The severity level of an AI insight.
enum InsightSeverity {
  /// General information or observation.
  info,

  /// A potential risk or pattern to watch.
  warning,

  /// A critical pattern or high-probability signal.
  danger,
}

/// Represents a single insight generated by an AI provider.
@freezed
abstract class AiInsight with _$AiInsight {
  /// Creates an [AiInsight] with the given parameters.
  const factory AiInsight({
    /// The descriptive text of the insight.
    required String text,

    /// The type of pattern identified (e.g., "Bullish Engulfing").
    required String patternType,

    /// The severity of the insight.
    required InsightSeverity severity,
  }) = _AiInsight;
}
