name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Install dependencies
        run: dart pub get

      - name: Bootstrap
        run: dart run melos bootstrap

      - name: Format
        run: dart run melos run format

      - name: Analyze
        run: dart run melos run analyze

      - name: Test
        run: dart run melos run test
